Fix #2013010057 Fix error "qrc:/qml/FilesPlus/main.qml:78: TypeError: Result of expression 'appInfo.startMonitoring' [undefined] is not a function." by removing unused code as AppInfo have started mornitoring internally.